In [1]:
!pip3 install bs4

Requirement already satisfied: bs4 in /Users/mitchellcutmore/opt/anaconda3/lib/python3.9/site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in /Users/mitchellcutmore/opt/anaconda3/lib/python3.9/site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /Users/mitchellcutmore/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4->bs4) (2.2.1)

In [4]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

# 1 - pegar tudo do html

In [5]:
#URL to scrape
#url = 'https://www.wikiwand.com/en/Kylie_Minogue_singles_discography'

In [6]:
url = 'https://en.wikipedia.org/wiki/Kylie_Minogue_singles_discography'

In [7]:
df = pd.read_html(url)

In [8]:
df_80 = df[1]

In [9]:
df_80["Decade"] = "80"

In [10]:
df_80.head()

                       Title  Year Peak chart positions                       \
                       Title  Year               AUS[6] AUT[7] FRA[8] GER[9]
0            "Locomotion"[a]  1987                    1      —      —      —
1     "I Should Be So Lucky"  1987                    1      4      4      1
2        "Got to Be Certain"  1988                    1      —      9      6
3       "The Loco-Motion"[a]  1988                    —      3      5      3
4  "Je ne sais pas pourquoi"  1988                   11      —     15     14

                                                    \
  IRE[10] NZ[11] SWI[12] UK[13] US[14] USDance[15]
0       —      8       —      —      —           —
1       1      3       1      1     28          10
2       4      2       8      2      —           —
3       1      —       2      2      3          12
4       2      9      24      2      —           —

                             Sales  \
                             Sales
0                              NaN
1  JPN: 30,140[19] UK: 702,850[20]
2                  UK: 315,000[25]
3  JPN: 24,530[19] UK: 434,000[20]
4                  UK: 325,000[25]

                                      Certifications             Album  \
                                      Certifications             Album
0                                 ARIA: Platinum[18]  Non-album single
1  ARIA: Platinum[21] BPI: Gold[22] BVMI: Gold[23...             Kylie
2    ARIA: Gold[26] BPI: Silver[22] SNEP: Silver[24]             Kylie
3                       BPI: Gold[22] RIAA: Gold[27]             Kylie
4                                    BPI: Silver[22]             Kylie

  Unnamed: 15_level_0 Decade
  Unnamed: 15_level_1
0                 NaN     80
1                 NaN     80
2                 NaN     80
3                 NaN     80
4                 NaN     80

In [11]:
#identificar todas as colunas
df_80.columns

MultiIndex([(               'Title',               'Title'),
            (                'Year',                'Year'),
            ('Peak chart positions',              'AUS[6]'),
            ('Peak chart positions',              'AUT[7]'),
            ('Peak chart positions',              'FRA[8]'),
            ('Peak chart positions',              'GER[9]'),
            ('Peak chart positions',             'IRE[10]'),
            ('Peak chart positions',              'NZ[11]'),
            ('Peak chart positions',             'SWI[12]'),
            ('Peak chart positions',              'UK[13]'),
            ('Peak chart positions',              'US[14]'),
            ('Peak chart positions',         'USDance[15]'),
            (               'Sales',               'Sales'),
            (      'Certifications',      'Certifications'),
            (               'Album',               'Album'),
            ( 'Unnamed: 15_level_0', 'Unnamed: 15_level_1'),
            (              'Decade',                    '')],
           )

In [12]:
#limpar nomes das colunas
df_80.columns = ['Title',
            'Year',
            'Peak_AUS',
            'Peak_AUT',
            'Peak_FRA',
            'Peak_GER',
            'Peak_IRE',
            'Peak_NZ',
            'Peak_SWI',
            'Peak_UK',
            'Peak_US',
            'Peak_USDance',
            'Sales',
            'Certifications',
            'Album',
            'Unnamed',
            'Decade']

In [13]:
df_80.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Peak_USDance,Sales,Certifications,Album,Unnamed,Decade
0,"""Locomotion""[a]",1987,1,—,—,—,—,8,—,—,—,—,NaN,ARIA: Platinum[18],Non-album single,NaN,80
1,"""I Should Be So Lucky""",1987,1,4,4,1,1,3,1,1,28,10,"JPN: 30,140[19] UK: 702,850[20]",ARIA: Platinum[21] BPI: Gold[22] BVMI: Gold[23...,Kylie,NaN,80
2,"""Got to Be Certain""",1988,1,—,9,6,4,2,8,2,—,—,"UK: 315,000[25]",ARIA: Gold[26] BPI: Silver[22] SNEP: Silver[24],Kylie,NaN,80
3,"""The Loco-Motion""[a]",1988,—,3,5,3,1,—,2,2,3,12,"JPN: 24,530[19] UK: 434,000[20]",BPI: Gold[22] RIAA: Gold[27],Kylie,NaN,80
4,"""Je ne sais pas pourquoi""",1988,11,—,15,14,2,9,24,2,—,—,"UK: 325,000[25]",BPI: Silver[22],Kylie,NaN,80

In [14]:
#limpar colunas (drop Peak_USDance, Sales, Certifications, Unnamed)
df_80 = df_80.drop(['Peak_USDance', 'Sales', 'Certifications', 'Unnamed'], axis = 1)
#dropou inplace

In [15]:
df_80

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Album,Decade
0,"""Locomotion""[a]",1987,1,—,—,—,—,8,—,—,—,Non-album single,80
1,"""I Should Be So Lucky""",1987,1,4,4,1,1,3,1,1,28,Kylie,80
2,"""Got to Be Certain""",1988,1,—,9,6,4,2,8,2,—,Kylie,80
3,"""The Loco-Motion""[a]",1988,—,3,5,3,1,—,2,2,3,Kylie,80
4,"""Je ne sais pas pourquoi""",1988,11,—,15,14,2,9,24,2,—,Kylie,80
5,"""Especially for You"" (with Jason Donovan)",1988,2,12,3,10,1,2,2,1,—,Ten Good Reasons,80
6,"""It's No Secret""",1988,—,—,—,—,—,47,—,—,37,Kylie,80
7,"""Turn It into Love""[b]",1988,—,—,—,—,—,—,—,—,—,Kylie,80
8,"""Hand on Your Heart""",1989,4,—,8,17,1,15,6,1,—,Enjoy Yourself,80
9,"""Wouldn't Change a Thing""",1989,6,—,19,24,—,21,27,2,—,Enjoy Yourself,80
10,"""Never Too Late""",1989,14,—,26,45,1,27,23,4,—,Enjoy Yourself,80
11,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",80

# repetir processo para anos 90

In [16]:
df_90 = df[2]
df_90.head()

                         Title  Year Peak chart positions                \
                         Title  Year               AUS[6] AUT[7] FRA[8]
0         "Tears on My Pillow"  1990                   20      —      —
1  "Better the Devil You Know"  1990                    4     27     13
2          "Step Back in Time"  1990                    5      —     23
3       "What Do I Have to Do"  1991                   11      —     50
4                    "Shocked"  1991                    7      —      —

                                                              Sales  \
  GER[9] IRE[10] NZ[11] SWI[12] UK[13] USDance[15]            Sales
0     31       2     23       —      1           —  UK: 260,000[31]
1     24       4     27      21      2           —  UK: 340,000[20]
2     36       4     21      29      4           —              NaN
3     48       7      —     NaN      6           —              NaN
4      —       2      —       —      6           —              NaN

                   Certifications           Album Unnamed: 14_level_0
                   Certifications           Album Unnamed: 14_level_1
0                 BPI: Silver[22]  Enjoy Yourself                 NaN
1  ARIA: Gold[32] BPI: Silver[22]  Rhythm of Love                 NaN
2                  ARIA: Gold[30]  Rhythm of Love                 NaN
3                             NaN  Rhythm of Love                 NaN
4                  Rhythm of Love             NaN                 NaN

In [17]:
df_90["Decade"] = "90"
df_90.head()

                         Title  Year Peak chart positions                \
                         Title  Year               AUS[6] AUT[7] FRA[8]
0         "Tears on My Pillow"  1990                   20      —      —
1  "Better the Devil You Know"  1990                    4     27     13
2          "Step Back in Time"  1990                    5      —     23
3       "What Do I Have to Do"  1991                   11      —     50
4                    "Shocked"  1991                    7      —      —

                                                              Sales  \
  GER[9] IRE[10] NZ[11] SWI[12] UK[13] USDance[15]            Sales
0     31       2     23       —      1           —  UK: 260,000[31]
1     24       4     27      21      2           —  UK: 340,000[20]
2     36       4     21      29      4           —              NaN
3     48       7      —     NaN      6           —              NaN
4      —       2      —       —      6           —              NaN

                   Certifications           Album Unnamed: 14_level_0 Decade
                   Certifications           Album Unnamed: 14_level_1
0                 BPI: Silver[22]  Enjoy Yourself                 NaN     90
1  ARIA: Gold[32] BPI: Silver[22]  Rhythm of Love                 NaN     90
2                  ARIA: Gold[30]  Rhythm of Love                 NaN     90
3                             NaN  Rhythm of Love                 NaN     90
4                  Rhythm of Love             NaN                 NaN     90

In [18]:
df_90.columns = ['Title',
            'Year',
            'Peak_AUS',
            'Peak_AUT',
            'Peak_FRA',
            'Peak_GER',
            'Peak_IRE',
            'Peak_NZ',
            'Peak_SWI',
            'Peak_UK',
            'Peak_USDance',
            'Sales',
            'Certifications',
            'Album',
            'Unnamed',
            'Decade']

df_90.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_USDance,Sales,Certifications,Album,Unnamed,Decade
0,"""Tears on My Pillow""",1990,20,—,—,31,2,23,—,1,—,"UK: 260,000[31]",BPI: Silver[22],Enjoy Yourself,NaN,90
1,"""Better the Devil You Know""",1990,4,27,13,24,4,27,21,2,—,"UK: 340,000[20]",ARIA: Gold[32] BPI: Silver[22],Rhythm of Love,NaN,90
2,"""Step Back in Time""",1990,5,—,23,36,4,21,29,4,—,NaN,ARIA: Gold[30],Rhythm of Love,NaN,90
3,"""What Do I Have to Do""",1991,11,—,50,48,7,—,NaN,6,—,NaN,NaN,Rhythm of Love,NaN,90
4,"""Shocked""",1991,7,—,—,—,2,—,—,6,—,NaN,Rhythm of Love,NaN,NaN,90

In [19]:
df_90.drop(['Peak_USDance', 'Sales', 'Certifications', 'Unnamed'], axis = 1)

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Album,Decade
0,"""Tears on My Pillow""",1990,20,—,—,31,2,23,—,1,Enjoy Yourself,90
1,"""Better the Devil You Know""",1990,4,27,13,24,4,27,21,2,Rhythm of Love,90
2,"""Step Back in Time""",1990,5,—,23,36,4,21,29,4,Rhythm of Love,90
3,"""What Do I Have to Do""",1991,11,—,50,48,7,—,NaN,6,Rhythm of Love,90
4,"""Shocked""",1991,7,—,—,—,2,—,—,6,NaN,90
5,"""Word Is Out""",1991,10,—,—,—,8,—,—,16,Let's Get to It,90
6,"""If You Were with Me Now"" (with Keith Washington)",1991,23,—,—,61,7,—,—,4,Let's Get to It,90
7,"""Give Me Just a Little More Time""",1992,24,—,—,51,6,—,—,2,Let's Get to It,90
8,"""Finer Feelings""",1992,60,—,—,—,16,—,—,11,Let's Get to It,90
9,"""What Kind of Fool (Heard All That Before)""",1992,17,—,—,81,22,—,—,14,Greatest Hits,90
10,"""Celebration""",1992,21,—,—,—,11,—,—,20,Greatest Hits,90
11,"""Confide in Me""",1994,1,—,10,50,12,12,20,2,Kylie Minogue,90
12,"""Put Yourself in My Place""",1994,11,—,—,87,—,—,—,11,Kylie Minogue,90
13,"""Where Is the Feeling?""",1995,31,—,—,—,—,—,—,16,NaN,90
14,"""Where the Wild Roses Grow"" (with Nick Cave an...",1995,2,4,37,12,6,11,11,11,Murder Ballads,90
15,"""Some Kind of Bliss""",1997,27,—,—,—,—,46,—,22,Impossible Princess,90
16,"""Did It Again""",1997,15,—,—,—,—,—,—,14,Impossible Princess,90
17,"""Breathe""",1998,23,—,—,—,—,—,—,14,Impossible Princess,90
18,"""Cowboy Style""",1998,39,—,—,—,—,—,—,—,Impossible Princess,90
19,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",90

# repetir processo para anos 00

In [20]:
df_00 = df[3]
df_00["Decade"] = "00"
df_00.head()

                          Title  Year Peak chart positions                \
                          Title  Year               AUS[6] AUT[7] FRA[8]
0             "Spinning Around"  2000                    1      —     28
1        "On a Night Like This"  2000                    1      —     69
2  "Kids"(with Robbie Williams)  2000                   14      —      —
3                 "Please Stay"  2000                   15      —      —
4        "Your Disco Needs You"  2001                   20     70      —

                                                                     Sales  \
  GER[9] IRE[10] NZ[11] SWI[12] UK[13] US[14] USDance[15]            Sales
0     62       4      2      34      1      —           —  UK: 314,000[20]
1     72      16     35      51      2      —           —  UK: 170,000[25]
2     47       9      5      35      2      —           —  UK: 235,000[25]
3      —      34      —       —     10      —           —              NaN
4     31       —      —      27    152      —           —   UK: 20,000[38]

                                    Certifications        Album  \
                                    Certifications        Album
0  ARIA: Platinum[35] BPI: Gold[22] RMNZ: Gold[36]  Light Years
1               ARIA: Platinum[35] BPI: Silver[22]  Light Years
2                   ARIA: Gold[37] BPI: Silver[22]  Light Years
3                                   ARIA: Gold[35]  Light Years
4                                      Light Years          NaN

  Unnamed: 15_level_0 Decade
  Unnamed: 15_level_1
0                 NaN     00
1                 NaN     00
2                 NaN     00
3                 NaN     00
4                 NaN     00

In [21]:
df_00.columns = ['Title',
            'Year',
            'Peak_AUS',
            'Peak_AUT',
            'Peak_FRA',
            'Peak_GER',
            'Peak_IRE',
            'Peak_NZ',
            'Peak_SWI',
            'Peak_UK',
            'Peak_US',
            'Peak_USDance',
            'Sales',
            'Certifications',
            'Album',
            'Unnamed',
            'Decade']
df_00.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Peak_USDance,Sales,Certifications,Album,Unnamed,Decade
0,"""Spinning Around""",2000,1,—,28,62,4,2,34,1,—,—,"UK: 314,000[20]",ARIA: Platinum[35] BPI: Gold[22] RMNZ: Gold[36],Light Years,NaN,00
1,"""On a Night Like This""",2000,1,—,69,72,16,35,51,2,—,—,"UK: 170,000[25]",ARIA: Platinum[35] BPI: Silver[22],Light Years,NaN,00
2,"""Kids""(with Robbie Williams)",2000,14,—,—,47,9,5,35,2,—,—,"UK: 235,000[25]",ARIA: Gold[37] BPI: Silver[22],Light Years,NaN,00
3,"""Please Stay""",2000,15,—,—,—,34,—,—,10,—,—,NaN,ARIA: Gold[35],Light Years,NaN,00
4,"""Your Disco Needs You""",2001,20,70,—,31,—,—,27,152,—,—,"UK: 20,000[38]",Light Years,NaN,NaN,00

In [22]:
df_00 = df_00.drop(['Peak_USDance', 'Sales', 'Certifications', 'Unnamed'], axis = 1)
df_00.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Album,Decade
0,"""Spinning Around""",2000,1,—,28,62,4,2,34,1,—,Light Years,00
1,"""On a Night Like This""",2000,1,—,69,72,16,35,51,2,—,Light Years,00
2,"""Kids""(with Robbie Williams)",2000,14,—,—,47,9,5,35,2,—,Light Years,00
3,"""Please Stay""",2000,15,—,—,—,34,—,—,10,—,Light Years,00
4,"""Your Disco Needs You""",2001,20,70,—,31,—,—,27,152,—,NaN,00

# repetir para os anos 10

In [23]:
df_10 = df[4]
df_10["Decade"] = "10"
df_10.head()

                                    Title  Year Peak chart positions         \
                                    Title  Year               AUS[6] AUT[7]
0                        "All the Lovers"  2010                   13      5
1                      "Get Outta My Way"  2010                   69     61
2                     "Better than Today"  2010                   55      —
3  "Put Your Hands Up (If You Feel Love)"  2011                   50     38
4                              "Timebomb"  2012                   12     58

                                                                       \
  FRA[8] GER[9] IRE[10] NZ[11] SWI[12] UK[13] USDance[15] USSales[55]
0      3     10       6      —       6      3           1           4
1     29     41      33      —      61     12           1           7
2     63      —       —      —       —     32           1          14
3      —      —       —      —       —     93           1           4
4     46     56      26     33       —     31           1           4

                            Sales  \
                            Sales
0                 UK: 383,000[20]
1  UK: 100,000[20] US: 66,000[42]
2                             NaN
3                             NaN
4                             NaN

                                Certifications             Album Decade
                                Certifications             Album
0  ARIA: Gold[56] BPI: Gold[22] FIMI: Gold[57]         Aphrodite     10
1                                          NaN         Aphrodite     10
2                                          NaN         Aphrodite     10
3                                          NaN         Aphrodite     10
4                               FIMI: Gold[57]  Non-album single     10

In [24]:
df_10.columns = ['Title',
            'Year',
            'Peak_AUS',
            'Peak_AUT',
            'Peak_FRA',
            'Peak_GER',
            'Peak_IRE',
            'Peak_NZ',
            'Peak_SWI',
            'Peak_UK',
            'Peak_USDance',
            'US Sales',   
            'Sales',
            'Certifications',
            'Album',
            'Decade']

In [25]:
df_10.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_USDance,US Sales,Sales,Certifications,Album,Decade
0,"""All the Lovers""",2010,13,5,3,10,6,—,6,3,1,4,"UK: 383,000[20]",ARIA: Gold[56] BPI: Gold[22] FIMI: Gold[57],Aphrodite,10
1,"""Get Outta My Way""",2010,69,61,29,41,33,—,61,12,1,7,"UK: 100,000[20] US: 66,000[42]",NaN,Aphrodite,10
2,"""Better than Today""",2010,55,—,63,—,—,—,—,32,1,14,NaN,NaN,Aphrodite,10
3,"""Put Your Hands Up (If You Feel Love)""",2011,50,38,—,—,—,—,—,93,1,4,NaN,NaN,Aphrodite,10
4,"""Timebomb""",2012,12,58,46,56,26,33,—,31,1,4,NaN,FIMI: Gold[57],Non-album single,10

In [26]:
df_10.drop(['US Sales', 'Sales', 'Certifications'], axis = 1)

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_USDance,Album,Decade
0,"""All the Lovers""",2010,13,5,3,10,6,—,6,3,1,Aphrodite,10
1,"""Get Outta My Way""",2010,69,61,29,41,33,—,61,12,1,Aphrodite,10
2,"""Better than Today""",2010,55,—,63,—,—,—,—,32,1,Aphrodite,10
3,"""Put Your Hands Up (If You Feel Love)""",2011,50,38,—,—,—,—,—,93,1,Aphrodite,10
4,"""Timebomb""",2012,12,58,46,56,26,33,—,31,1,Non-album single,10
5,"""Flower""",2012,—,—,—,—,—,—,—,96,—,The Abbey Road Sessions,10
6,"""Limpido"" (with Laura Pausini)",2013,—,—,—,—,—,—,66,—,—,20 – The Greatest Hits,10
7,"""Into the Blue""",2014,46,37,47,31,9,—,32,12,1,Kiss Me Once,10
8,"""I Was Gonna Cancel""",2014,—,—,—,—,—,—,—,59,5,NaN,10
9,"""Crystallize""",2014,115,—,139,—,88,—,—,60,—,Non-album single,10
10,"""Only You""(with James Corden)",2015,—,—,—,—,—,—,—,155,—,Kylie Christmas,10
11,"""100 Degrees""(with Dannii Minogue)",2015,—,—,—,—,—,—,—,—,—,Kylie Christmas,10
12,"""Every Day's Like Christmas""",2015,—,—,—,—,—,—,—,—,—,Kylie Christmas,10
13,"""At Christmas""",2016,—,—,—,—,—,—,—,—,—,Kylie Christmas: Snow Queen Edition,10
14,"""Wonderful Christmastime""(with Mika)",2016,—,—,—,—,—,—,—,—,—,Kylie Christmas: Snow Queen Edition,10
15,"""Dancing""",2018,46,—,—,71,—,—[d],—,38,1,Golden,10
16,"""Stop Me from Falling""",2018,164[e],—,—,—,—,—,—,52,—,NaN,10
17,"""Golden""",2018,—,—,—,—,—,—,—,—[f],—,Golden,10
18,"""A Lifetime to Repair""",2018,—,—,—,—,—,—,—,—[g],—,Golden,10
19,"""Music's Too Sad Without You""(with Jack Savore...",2018,—,—,—,—,—,—,—,—[h],—,Golden,10
20,"""Sincerely Yours""",2018,—,—,—,—,—,—,—,—,—,Golden,10
21,"""New York City""",2019,—[i],—,—,—,—,—,—,—[j],—,Step Back in Time: The Definitive Collection,10
22,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",10

# repetir para os anos 20

In [27]:
df_20 = df[5]
df_20["Decade"] = "20"
df_20.head()

                                               Title  Year  \
                                               Title  Year
0                                    "Say Something"  2020
1                                            "Magic"  2020
2  "Real Groove"(solo or Studio 2054 Remix with D...  2020
3  "Starstruck (Kylie Minogue Remix)"(with Years ...  2021
4         "A Second to Midnight"(with Years & Years)  2021

  Peak chart positions                                                \
     AUSDig. Sales[71] BEL (FL)[72] IRE[10] NZHot[73] SCO[74] UK[13]
0                    5           14       —        40       3     56
1                    5           17       —        28       2     53
2                    —            —       —         8       —     95
3                    —           80      55        24       —     31
4                    —            —       —         —       —   —[k]

                                                          Sales  \
  UKIndie[75] USDance/Elec.[76] USDanceAir.[77]           Sales
0           8                18              35  UK: 75,555[78]
1           7                17               —  UK: 46,986[78]
2          22                15               —  UK: 24,730[78]
3          31                18               —             NaN
4          27                26               —             NaN

                       Album Decade
                       Album
0                      Disco     20
1                      Disco     20
2                      Disco     20
3                 Night Call     20
4  Disco: Guest List Edition     20

In [28]:
df_20.columns = ['Title',
            'Year',
            'Peak_AUS',
            'Peak_BEL',     
            'Peak_IRE',
            'Peak_NZ',
            'Peak_SCO',
            'Peak_UK',
            'Peak_UKIndie',     
            'Peak_USDance',
            'Peak_US Airplay',   
            'Sales',
            'Album',
            'Decade']

df_20.head()

,Title,Year,Peak_AUS,Peak_BEL,Peak_IRE,Peak_NZ,Peak_SCO,Peak_UK,Peak_UKIndie,Peak_USDance,Peak_US Airplay,Sales,Album,Decade
0,"""Say Something""",2020,5,14,—,40,3,56,8,18,35,"UK: 75,555[78]",Disco,20
1,"""Magic""",2020,5,17,—,28,2,53,7,17,—,"UK: 46,986[78]",Disco,20
2,"""Real Groove""(solo or Studio 2054 Remix with D...",2020,—,—,—,8,—,95,22,15,—,"UK: 24,730[78]",Disco,20
3,"""Starstruck (Kylie Minogue Remix)""(with Years ...",2021,—,80,55,24,—,31,31,18,—,NaN,Night Call,20
4,"""A Second to Midnight""(with Years & Years)",2021,—,—,—,—,—,—[k],27,26,—,NaN,Disco: Guest List Edition,20

In [29]:
#conscious deciosion here to keep only one chart per country and prioritise the more generalist chart (rather than US Dance or UK indie)
df_20 = df_20.drop(['Peak_UKIndie', 'Peak_US Airplay', 'Sales'], axis = 1)
df_20.head()

,Title,Year,Peak_AUS,Peak_BEL,Peak_IRE,Peak_NZ,Peak_SCO,Peak_UK,Peak_USDance,Album,Decade
0,"""Say Something""",2020,5,14,—,40,3,56,18,Disco,20
1,"""Magic""",2020,5,17,—,28,2,53,17,Disco,20
2,"""Real Groove""(solo or Studio 2054 Remix with D...",2020,—,—,—,8,—,95,15,Disco,20
3,"""Starstruck (Kylie Minogue Remix)""(with Years ...",2021,—,80,55,24,—,31,18,Night Call,20
4,"""A Second to Midnight""(with Years & Years)",2021,—,—,—,—,—,—[k],26,Disco: Guest List Edition,20

In [30]:
df_20.columns

Index(['Title', 'Year', 'Peak_AUS', 'Peak_BEL', 'Peak_IRE', 'Peak_NZ',
       'Peak_SCO', 'Peak_UK', 'Peak_USDance', 'Album', 'Decade'],
      dtype='object')

# Unir todas as tabelas com concat

In [31]:
pd.concat([df_80, df_20], axis=0)

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Album,Decade,Peak_BEL,Peak_SCO,Peak_USDance
0,"""Locomotion""[a]",1987,1,—,—,—,—,8,—,—,—,Non-album single,80,NaN,NaN,NaN
1,"""I Should Be So Lucky""",1987,1,4,4,1,1,3,1,1,28,Kylie,80,NaN,NaN,NaN
2,"""Got to Be Certain""",1988,1,—,9,6,4,2,8,2,—,Kylie,80,NaN,NaN,NaN
3,"""The Loco-Motion""[a]",1988,—,3,5,3,1,—,2,2,3,Kylie,80,NaN,NaN,NaN
4,"""Je ne sais pas pourquoi""",1988,11,—,15,14,2,9,24,2,—,Kylie,80,NaN,NaN,NaN
5,"""Especially for You"" (with Jason Donovan)",1988,2,12,3,10,1,2,2,1,—,Ten Good Reasons,80,NaN,NaN,NaN
6,"""It's No Secret""",1988,—,—,—,—,—,47,—,—,37,Kylie,80,NaN,NaN,NaN
7,"""Turn It into Love""[b]",1988,—,—,—,—,—,—,—,—,—,Kylie,80,NaN,NaN,NaN
8,"""Hand on Your Heart""",1989,4,—,8,17,1,15,6,1,—,Enjoy Yourself,80,NaN,NaN,NaN
9,"""Wouldn't Change a Thing""",1989,6,—,19,24,—,21,27,2,—,Enjoy Yourself,80,NaN,NaN,NaN
10,"""Never Too Late""",1989,14,—,26,45,1,27,23,4,—,Enjoy Yourself,80,NaN,NaN,NaN
11,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",80,NaN,NaN,NaN
0,"""Say Something""",2020,5,NaN,NaN,NaN,—,40,NaN,56,NaN,Disco,20,14,3,18
1,"""Magic""",2020,5,NaN,NaN,NaN,—,28,NaN,53,NaN,Disco,20,17,2,17
2,"""Real Groove""(solo or Studio 2054 Remix with D...",2020,—,NaN,NaN,NaN,—,8,NaN,95,NaN,Disco,20,—,—,15
3,"""Starstruck (Kylie Minogue Remix)""(with Years ...",2021,—,NaN,NaN,NaN,55,24,NaN,31,NaN,Night Call,20,80,—,18
4,"""A Second to Midnight""(with Years & Years)",2021,—,NaN,NaN,NaN,—,—,NaN,—[k],NaN,Disco: Guest List Edition,20,—,—,26
5,"""Kiss of Life""(with Jessie Ware)",2021,—,NaN,NaN,NaN,—,—,NaN,—[l],NaN,Disco: Guest List Edition,20,—,—,49
6,"""Can't Stop Writing Songs About You""(with Glor...",2022,—,NaN,NaN,NaN,—,—,NaN,—[m],NaN,Disco: Guest List Edition,20,—,—,—
7,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",NaN,NaN,NaN,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...",NaN,"""—"" denotes a title that did not chart, or was...",NaN,"""—"" denotes a title that did not chart, or was...",20,"""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was...","""—"" denotes a title that did not chart, or was..."

In [32]:
df_concat = pd.concat([df_80, df_90, df_00, df_10, df_20], axis=0)

In [33]:
df_concat.head()

,Title,Year,Peak_AUS,Peak_AUT,Peak_FRA,Peak_GER,Peak_IRE,Peak_NZ,Peak_SWI,Peak_UK,Peak_US,Album,Decade,Peak_USDance,Sales,Certifications,Unnamed,US Sales,Peak_BEL,Peak_SCO
0,"""Locomotion""[a]",1987,1,—,—,—,—,8,—,—,—,Non-album single,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"""I Should Be So Lucky""",1987,1,4,4,1,1,3,1,1,28,Kylie,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"""Got to Be Certain""",1988,1,—,9,6,4,2,8,2,—,Kylie,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""The Loco-Motion""[a]",1988,—,3,5,3,1,—,2,2,3,Kylie,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"""Je ne sais pas pourquoi""",1988,11,—,15,14,2,9,24,2,—,Kylie,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_concat.to_csv('Kyliepedia.csv', index=False)

In [35]:
df_concat.to_excel('Kyliepedia.xlsx', index=False)

# analisei as outras tabelas

...cobrindo faixas promocionais, colaborações, etc mas vendo os numeros aqui, tomei a decisão de focar nas tabelas das cinco decadas cobrindo o eixo principal da discografia da Kylie

In [36]:
df_test1 = df[6]
df_test1

                                               Title  \
                                               Title
0  "Keep on Pumpin' It" (Visionmasters and Tony K...
1  "GBI (German Bold Italic)" (Towa Tei featuring...
2  "Sometime Samurai" (Towa Tei featuring Kylie M...
3        "Higher"(Taio Cruz featuring Kylie Minogue)
4  "Beautiful"(Enrique Iglesias featuring Kylie M...
5  "Right Here, Right Now" (Giorgio Moroder featu...
6  "The Other Boys" (Nervo featuring Kylie Minogu...
7  "Really Don't Like U"(Tove Lo featuring Kylie ...
8  "On oublie le reste"(Jenifer featuring Kylie M...
9  "—" denotes a title that did not chart, or was...

                                                Year  \
                                                Year
0                                               1991
1                                               1997
2                                               2005
3                                               2010
4                                               2014
5                                               2015
6                                               2015
7                                               2019
8                                               2019
9  "—" denotes a title that did not chart, or was...

                                Peak chart positions  \
                                              AUS[6]
0                                                  —
1                                                 50
2                                                  —
3                                                 25
4                                                 47
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              AUT[7]
0                                                  —
1                                                  —
2                                                  —
3                                                  3
4                                                  —
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              FRA[8]
0                                                  —
1                                                  —
2                                                  —
3                                                  7
4                                                  —
5                                                147
6                                                  —
7                                                  —
8                                               —[q]
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              GER[9]
0                                                  —
1                                                  —
2                                                  —
3                                                  3
4                                                  —
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                             IRE[10]
0                                                  —
1                                                  —
2                                                  —
3                                                  7
4                                                  —
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              NZ[11]
0                                                  —
1                                                  —
2                                                  —
3                                                  5
4                                                  —
5                                                  —
6                                                  —
7                                               —[o]
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                             SWI[12]
0                                                  —
1                                                  —
2                                                  —
3                                                  4
4                                                  —
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              UK[13]
0                                                 49
1                                                 63
2                                                  —
3                                                  8
4                                                  —
5                                               —[n]
6                                                  —
7                                               —[p]
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                              US[14]
0                                                  —
1                                                  —
2                                                  —
3                                                  —
4                                                  —
5                                                  —
6                                                  —
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                                      \
                                         USDance[15]
0                                                  —
1                                                  —
2                                                  —
3                                                  1
4                                                  —
5                                                  1
6                                                  1
7                                                  —
8                                                  —
9  "—" denotes a title that did not chart, or was...

                                               Sales  \
                                               Sales
0                                                NaN
1                                                NaN
2                                                NaN
3                                    UK: 338,000[20]
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9  "—" denotes a title that did not chart, or was...

                                      Certifications  \
                                      Certifications
0                                                NaN
1                                                NaN
2                                                NaN
3  ARIA: Gold[83] BPI: Gold[84] GLF: Gold[85] IFP...
4                                                NaN
5                                                NaN
6                                                NaN
7                                                NaN
8                                                NaN
9  "—" denotes a title that did not chart, or was...

                                               Album
                                               Album
0                                   Non-album single
1                                       Sound Museum
2                                              Flash
3                                           Rokstarr
4                                       Sex and Love
5                                            Déjà Vu
6                                         Collateral
7                                     Sunshine Kitty
8                     Nouvelle page (Deluxe Version)
9  "—" denotes a title that did not chart, or was...

In [37]:
df_test2 = df[7]
df_test2

                                               Title  \
                                               Title
0  "A World Without Music"[95] (amongst Hearing Aid)
1  "Do They Know It's Christmas?"(amongst Band Ai...
2                "Monkey Man"[97] (with The Wiggles)
3          "Everybody Hurts" (amongst Helping Haiti)
4                     "We Are One"[99] (with Verbal)
5   "God Only Knows" (amongst BBC Music and Friends)
6  "Stop Crying Your Heart Out"(as BBC Radio 2's ...
7  "—" denotes a title that did not chart, or was...

                                                Year  \
                                                Year
0                                               1985
1                                               1989
2                                               2009
3                                               2010
4                                               2011
5                                               2014
6                                               2020
7  "—" denotes a title that did not chart, or was...

                                Peak chart positions  \
                                             AUS[92]
0                                                  —
1                                                 30
2                                                  —
3                                                 28
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                             AUT[93]
0                                                  —
1                                                  —
2                                                  —
3                                                 23
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                             GER[94]
0                                                  —
1                                                 74
2                                                  —
3                                                 16
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                             IRE[10]
0                                                  —
1                                                  1
2                                                  —
3                                                  1
4                                                  —
5                                                 77
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                              NZ[11]
0                                                  —
1                                                  8
2                                                  —
3                                                 17
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                                 SWE
0                                                  —
1                                                 15
2                                                  —
3                                                 21
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                             SWI[12]
0                                                  —
1                                                  —
2                                                  —
3                                                 16
4                                                  —
5                                                  —
6                                                  —
7  "—" denotes a title that did not chart, or was...

                                                      \
                                              UK[13]
0                                                  —
1                                                  1
2                                                  —
3                                                  1
4                                                  —
5                                                 20
6                                                  7
7  "—" denotes a title that did not chart, or was...

                                      Certifications  \
                                      Certifications
0                                                NaN
1                                  BPI: Platinum[96]
2                                                NaN
3                                  BPI: Platinum[98]
4                                                NaN
5                                                NaN
6                                                NaN
7  "—" denotes a title that did not chart, or was...

                                 Unnamed: 11_level_0  \
                                 Unnamed: 11_level_1
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7  "—" denotes a title that did not chart, or was...

                                 Unnamed: 12_level_0  \
                                 Unnamed: 12_level_1
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7  "—" denotes a title that did not chart, or was...

                                 Unnamed: 13_level_0  \
                                 Unnamed: 13_level_1
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7  "—" denotes a title that did not chart, or was...

                                 Unnamed: 14_level_0
                                 Unnamed: 14_level_1
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN
5                                                NaN
6                                                NaN
7  "—" denotes a title that did not chart, or was...

In [38]:
df_test3 = df[8]
df_test3

                                        Title  Year Peak chart positions  \
                                        Title  Year               AUS[6]
0               "I Guess I Like It Like That"  1991                  174
1                                   "Too Far"  1998                    —
2                                 "Butterfly"  2001                    —
3                                     "Fever"  2002                    —
4                 "Secret (Take You Home)"[r]  2004                    —
5                               "Promises"[s]  2004                    —
6     "Sensitized"[t](with Christophe Willem)  2009                    —
7                         "Whistle"(with múm)  2013                  391
8                                     "Skirt"  2013                    —
9                                 "Sexercize"  2014                    —
10                               "Golden Boy"  2014                    —
11                         "Million Miles"[u]  2014                    —
12                             "Sexy Love"[v]  2014                    —
13  "Absolutely Anything and Anything at All"  2015                    —
14                     "This Wheel's on Fire"  2016                    —
15                       "Raining Glitter"[w]  2018                  331
16                                "I Love It"  2020                    —
17                   "Dance Floor Darling"[x]  2021                    —
18                       "Marry The Night"[y]  2021                    —

                                                     \
   USDanceClub [15] USDance/Elec. [101] USSales[55]
0                 —                   —           —
1                 —                   —           —
2                14                   —           —
3                 —                   —           —
4                 —                   —           —
5                 —                   —           —
6                 —                   —           —
7                 —                   —           —
8                 1                  18          14
9                 —                  30           —
10                —                   —           —
11                —                   —           —
12                —                   —           —
13                —                   —           —
14                —                   —           —
15                —                   —           —
16                —                  38           —
17                —                   —           —
18                —                  24           —

                                  Album
                                  Album
0                       Let's Get to It
1                   Impossible Princess
2                           Light Years
3                                 Fever
4                         Body Language
5                         Body Language
6                               Caféine
7                          Jack & Diane
8                      Non-album single
9                          Kiss Me Once
10                         Kiss Me Once
11                         Kiss Me Once
12                         Kiss Me Once
13                  Absolutely Anything
14       Absolutely Fabulous: The Movie
15                               Golden
16                                Disco
17                                Disco
18  Born This Way The Tenth Anniversary

In [39]:
df_test4 = df[8]
df_test4

                                        Title  Year Peak chart positions  \
                                        Title  Year               AUS[6]
0               "I Guess I Like It Like That"  1991                  174
1                                   "Too Far"  1998                    —
2                                 "Butterfly"  2001                    —
3                                     "Fever"  2002                    —
4                 "Secret (Take You Home)"[r]  2004                    —
5                               "Promises"[s]  2004                    —
6     "Sensitized"[t](with Christophe Willem)  2009                    —
7                         "Whistle"(with múm)  2013                  391
8                                     "Skirt"  2013                    —
9                                 "Sexercize"  2014                    —
10                               "Golden Boy"  2014                    —
11                         "Million Miles"[u]  2014                    —
12                             "Sexy Love"[v]  2014                    —
13  "Absolutely Anything and Anything at All"  2015                    —
14                     "This Wheel's on Fire"  2016                    —
15                       "Raining Glitter"[w]  2018                  331
16                                "I Love It"  2020                    —
17                   "Dance Floor Darling"[x]  2021                    —
18                       "Marry The Night"[y]  2021                    —

                                                     \
   USDanceClub [15] USDance/Elec. [101] USSales[55]
0                 —                   —           —
1                 —                   —           —
2                14                   —           —
3                 —                   —           —
4                 —                   —           —
5                 —                   —           —
6                 —                   —           —
7                 —                   —           —
8                 1                  18          14
9                 —                  30           —
10                —                   —           —
11                —                   —           —
12                —                   —           —
13                —                   —           —
14                —                   —           —
15                —                   —           —
16                —                  38           —
17                —                   —           —
18                —                  24           —

                                  Album
                                  Album
0                       Let's Get to It
1                   Impossible Princess
2                           Light Years
3                                 Fever
4                         Body Language
5                         Body Language
6                               Caféine
7                          Jack & Diane
8                      Non-album single
9                          Kiss Me Once
10                         Kiss Me Once
11                         Kiss Me Once
12                         Kiss Me Once
13                  Absolutely Anything
14       Absolutely Fabulous: The Movie
15                               Golden
16                                Disco
17                                Disco
18  Born This Way The Tenth Anniversary

In [40]:
df_test5 = df[9]
df_test5

                                                Title  \
                                                Title
0                                     "White Diamond"
1                                 "Magnetic Electric"
2                                      "Speakerphone"
3                                        "Santa Baby"
4   "Black and White"(with Fernando Garibay featur...
5   "If I Can't Have You"(with Fernando Garibay fe...
6   "Your Body"(with Fernando Garibay featuring Gi...
7                                       "Night Fever"
8                                      "Miss a Thing"
9                                         "Supernova"
10            "—" denotes a title that did not chart.

                                       Year  \
                                       Year
0                                      2007
1                                      2007
2                                      2007
3                                      2007
4                                      2015
5                                      2015
6                                      2015
7                                      2016
8                                      2020
9                                      2020
10  "—" denotes a title that did not chart.

                                     Charts  \
                                     AUS[6]
0                                         —
1                                         —
2                                         —
3                                        44
4                                       NaN
5                                         —
6                                         —
7                                         —
8                                         —
9                                         —
10  "—" denotes a title that did not chart.

                                             \
                                   CAN[115]
0                                         —
1                                         —
2                                        87
3                                         —
4                                         —
5                                         —
6                                         —
7                                         —
8                                         —
9                                         —
10  "—" denotes a title that did not chart.

                                             \
                                     FRA[8]
0                                         —
1                                         —
2                                         —
3                                         —
4                                       140
5                                       168
6                                       174
7                                       159
8                                         —
9                                         —
10  "—" denotes a title that did not chart.

                                             \
                                UK[13][116]
0                                       114
1                                       176
2                                         —
3                                        31
4                                         —
5                                         —
6                                         —
7                                         —
8                                         —
9                                         —
10  "—" denotes a title that did not chart.

                                             \
                        USDance/Elec. [101]
0                                         —
1                                         —
2                                         —
3                                         —
4                                         —
5                                         —
6                                         —
7                                         —
8                                        30
9                                        48
10  "—" denotes a title that did not chart.

                                             \
                                   WW [117]
0                                         —
1                                         —
2                                         —
3                                        89
4                                         —
5                                         —
6                                         —
7                                         —
8                                         —
9                                         —
10  "—" denotes a title that did not chart.

                             Certifications  \
                             Certifications
0                                       NaN
1                                       NaN
2                                       NaN
3                         BPI: Platinum[22]
4                                       NaN
5                                       NaN
6                                       NaN
7                                       NaN
8                                       NaN
9                                       NaN
10  "—" denotes a title that did not chart.

                                      Album  \
                                      Album
0                                         X
1                                         X
2                                         X
3                         A Kylie Christmas
4                           Kylie + Garibay
5                           Kylie + Garibay
6                           Kylie + Garibay
7       Kylie Christmas: Snow Queen Edition
8                                     Disco
9                                     Disco
10  "—" denotes a title that did not chart.

                        Unnamed: 10_level_0
                        Unnamed: 10_level_1
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
5                                       NaN
6                                       NaN
7                                       NaN
8                                       NaN
9                                       NaN
10  "—" denotes a title that did not chart.

In [41]:
df_test6 = df[10]
df_test6

,Title,Year,Other artist(s),Album
0,"""In Denial""",1999,Pet Shop Boys,Nightlife
1,"""The Reflex""",1999,Ben Lee,Undone: The Songs of Duran Duran
2,"""G-House Project""",2001,Gerling,When Young Terrorists Chase the Sun
3,"""Bury Me Deep in Love""",2001,Jimmy Little,Corroboration
4,"""The Magic Roundabout""",2005,Andrea Remanda and Goldust,The Magic Roundabout
5,"""I Talk Too Much""",2007,Just Jack,Overtones
6,"""The Winner Takes It All""",2008,Dannii Minogue,Beautiful People: Soundtrack to the Hit BBC Se...
7,"""Chiggy Wiggy""",2009,Sonu Nigam and Suzanne D'Mello,Blue
8,"""Devotion""",2010,Hurts,Happiness
9,"""Crave You (Reprise)""",2014,Flight Facilities,Down to Earth
10,"""Should I Stay or Should I Go""",2014,Jools Holland,Sirens of Song
11,"""Still Feels Like the First Time""",2017,Zoot Woman,Absence
12,"""What You Waiting For""",2018,Sigala,Brighter Days
13,"""Lazy""",2019,The Vaccines,A Shaun the Sheep Movie: Farmageddon